"""Julia / ModelingToolkit backend: lower the IR into a generated ``.jl`` script.

This is the ``lower`` transformation from IR to the Julia analysis view. It
*generates source code* rather than serializing a compiled ``System`` object —
see ADR 0002. The generated script is a re-runnable, diffable artifact whose
source of truth remains the IR.

The emitted code targets **ModelingToolkit v11** idioms (see ADR 0004):

- explicit ``System(eqs, t)`` construction (no deprecated ``@mtkmodel`` DSL);
- ``mtkcompile`` instead of ``structural_simplify``;
- ``t``/``D`` imported as ``t_nounits`` / ``D_nounits``;
- parameter defaults attached via ``@parameters name = value`` (translated by
  MTK v11 into ``initial_conditions`` for constant values);
- inputs declared and passed to ``mtkcompile(sys; inputs = [...])``.
"""

from __future__ import annotations

from model_parser.backends.julia_expr import expr_to_julia, julia_model_slug, julia_number_literal
from model_parser.ir import IRModel

GENERATOR = "model-parser julia-mtk backend"


def emit_julia(ir: IRModel) -> str:
    """Generate a ModelingToolkit v11 Julia script that builds ``ir`` as a System."""
    name = julia_model_slug(ir)
    iv = ir.independent_variable
    lines: list[str] = []

    lines.append(f"# Generated by {GENERATOR}. Do not edit by hand.")
    lines.append("# Source of truth: the canonical IR. Regenerate after IR changes.")
    if ir.provenance is not None:
        lines.append(f"# IR tool: {ir.provenance.tool}")
        if ir.provenance.content_hash:
            lines.append(f"# IR content hash: {ir.provenance.content_hash}")
    lines.append(f"# IR version: {ir.ir_version}")
    lines.append("")
    lines.append("using ModelingToolkit")
    lines.append(f"using ModelingToolkit: t_nounits as {iv}, D_nounits as D")
    lines.append("")
    lines.append(f'"""Build the `{ir.model.name}` model as a compiled MTK `System`."""')
    lines.append(f"function build_{name}()")

    # Parameters with defaults.
    if ir.parameters:
        decls = []
        for param in ir.parameters:
            if param.default is None:
                decls.append(param.name)
            else:
                decls.append(f"{param.name} = {julia_number_literal(param.default)}")
        lines.append(f"    @parameters {' '.join(decls)}")

    # Time-dependent variables: states, inputs, outputs, locals.
    tvars = (
        [v.name for v in ir.states]
        + [v.name for v in ir.inputs]
        + [v.name for v in ir.outputs]
        + [local.name for local in ir.locals]
    )
    if tvars:
        decls = " ".join(f"{n}({iv})" for n in tvars)
        lines.append(f"    @variables {decls}")

    lines.append("")
    lines.append("    eqs = [")
    for local in ir.locals:
        lines.append(f"        {local.name} ~ {expr_to_julia(local.expr)},")
    for diff in ir.equations.differential:
        lines.append(f"        D({diff.state}) ~ {expr_to_julia(diff.rhs)},")
    for out in ir.equations.outputs:
        lines.append(f"        {out.output} ~ {expr_to_julia(out.rhs)},")
    lines.append("    ]")
    lines.append("")
    lines.append(f"    @named {name} = System(eqs, {iv})")

    if ir.inputs:
        input_list = ", ".join(v.name for v in ir.inputs)
        lines.append(f"    return mtkcompile({name}; inputs = [{input_list}])")
    else:
        lines.append(f"    return mtkcompile({name})")

    lines.append("end")
    lines.append("")
    return "\n".join(lines)
