"""Julia / ModelingToolkit backend: lower the IR into a generated ``.jl`` script.

This is the ``lower`` transformation from IR to the Julia analysis view. It
*generates source code* rather than serializing a compiled ``System`` object —
see ADR 0002. The generated script is a re-runnable, diffable artifact whose
source of truth remains the IR.

The emitted code targets **ModelingToolkit v11** idioms (see ADR 0004):

- explicit ``System(eqs, t)`` construction (no deprecated ``@mtkmodel`` DSL);
- ``mtkcompile`` instead of ``structural_simplify``;
- ``t``/``D`` imported as ``t_nounits`` / ``D_nounits``;
- parameter defaults attached via ``@parameters name = value`` (translated by
  MTK v11 into ``initial_conditions`` for constant values);
- inputs declared and passed to ``mtkcompile(sys; inputs = [...])``.
"""

from __future__ import annotations

from model_parser.ir import Call, Expr, IRModel, Num, Sym

GENERATOR = "model-parser julia-mtk backend"

# IR op name -> Julia infix operator.
_INFIX: dict[str, str] = {
    "+": "+",
    "-": "-",
    "*": "*",
    "/": "/",
    "^": "^",
    "==": "==",
    "!=": "!=",
    "<": "<",
    ">": ">",
    "<=": "<=",
    ">=": ">=",
}

# IR op name -> Julia function name.
_FUNCS: dict[str, str] = {
    "max": "max",
    "min": "min",
    "sqrt": "sqrt",
    "exp": "exp",
    "log": "log",
    "abs": "abs",
    "ifelse": "ifelse",
}


class JuliaCodegenError(ValueError):
    """Raised when an IR construct cannot be lowered to Julia."""


def expr_to_julia(expr: Expr) -> str:
    """Render an IR expression as a parenthesized Julia expression string."""
    if isinstance(expr, Num):
        return _render_number(expr.value)
    if isinstance(expr, Sym):
        return expr.name
    if isinstance(expr, Call):
        return _render_call(expr)
    raise JuliaCodegenError(f"unknown expression node: {expr!r}")


def _render_number(value: float) -> str:
    if value.is_integer():
        return f"{value:.1f}"
    return repr(value)


def _render_call(call: Call) -> str:
    op = call.op
    args = call.args
    if op == "neg":
        if len(args) != 1:
            raise JuliaCodegenError("'neg' expects exactly one argument")
        return f"(-{expr_to_julia(args[0])})"
    if op in _INFIX:
        if len(args) != 2:
            raise JuliaCodegenError(f"operator {op!r} expects two arguments")
        left, right = (expr_to_julia(a) for a in args)
        return f"({left} {_INFIX[op]} {right})"
    if op in _FUNCS:
        rendered = ", ".join(expr_to_julia(a) for a in args)
        return f"{_FUNCS[op]}({rendered})"
    raise JuliaCodegenError(f"unsupported operator/function {op!r}")


def _julia_name(ir: IRModel) -> str:
    name = ir.model.name or "model"
    cleaned = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name)
    if not cleaned or not (cleaned[0].isalpha() or cleaned[0] == "_"):
        cleaned = f"m_{cleaned}"
    return cleaned


def emit_julia(ir: IRModel) -> str:
    """Generate a ModelingToolkit v11 Julia script that builds ``ir`` as a System."""
    name = _julia_name(ir)
    iv = ir.independent_variable
    lines: list[str] = []

    lines.append(f"# Generated by {GENERATOR}. Do not edit by hand.")
    lines.append("# Source of truth: the canonical IR. Regenerate after IR changes.")
    if ir.provenance is not None:
        lines.append(f"# IR tool: {ir.provenance.tool}")
        if ir.provenance.content_hash:
            lines.append(f"# IR content hash: {ir.provenance.content_hash}")
    lines.append(f"# IR version: {ir.ir_version}")
    lines.append("")
    lines.append("using ModelingToolkit")
    lines.append(f"using ModelingToolkit: t_nounits as {iv}, D_nounits as D")
    lines.append("")
    lines.append(f'"""Build the `{ir.model.name}` model as a compiled MTK `System`."""')
    lines.append(f"function build_{name}()")

    # Parameters with defaults.
    if ir.parameters:
        decls = []
        for param in ir.parameters:
            if param.default is None:
                decls.append(param.name)
            else:
                decls.append(f"{param.name} = {_render_number(param.default)}")
        lines.append(f"    @parameters {' '.join(decls)}")

    # Time-dependent variables: states, inputs, outputs, locals.
    tvars = (
        [v.name for v in ir.states]
        + [v.name for v in ir.inputs]
        + [v.name for v in ir.outputs]
        + [local.name for local in ir.locals]
    )
    if tvars:
        decls = " ".join(f"{n}({iv})" for n in tvars)
        lines.append(f"    @variables {decls}")

    lines.append("")
    lines.append("    eqs = [")
    for local in ir.locals:
        lines.append(f"        {local.name} ~ {expr_to_julia(local.expr)},")
    for diff in ir.equations.differential:
        lines.append(f"        D({diff.state}) ~ {expr_to_julia(diff.rhs)},")
    for out in ir.equations.outputs:
        lines.append(f"        {out.output} ~ {expr_to_julia(out.rhs)},")
    lines.append("    ]")
    lines.append("")
    lines.append(f"    @named {name} = System(eqs, {iv})")

    if ir.inputs:
        input_list = ", ".join(v.name for v in ir.inputs)
        lines.append(f"    return mtkcompile({name}; inputs = [{input_list}])")
    else:
        lines.append(f"    return mtkcompile({name})")

    lines.append("end")
    lines.append("")
    return "\n".join(lines)
