"""Julia numerical RHS backend: IR -> plain in-place vector field ``f!`` (+ optional ``outputs!``).

This complements the ModelingToolkit view: the same IR is lowered to a
SciML-style ``f!(du, u, p, t)`` (and ``outputs!`` when output equations exist)
for workflows that need an explicit numerical ODE RHS without building an MTK
``System``. See ADR 0006.
"""

from __future__ import annotations

from model_parser.backends.julia_expr import JuliaCodegenError, expr_to_julia, julia_model_slug
from model_parser.ir import IRModel

GENERATOR = "model-parser julia-rhs backend"


def emit_julia_rhs(ir: IRModel) -> str:
    """Generate a Julia module fragment defining ``f_<slug>!`` and optional ``outputs_<slug>!``.

    **Vector conventions** (1-based indices, matching Julia):

    - ``u[i]`` follows ``ir.states`` declaration order.
    - ``p[i]`` follows ``ir.parameters`` declaration order (values only; defaults
      in the IR are documentation for callers, not applied inside ``f!``).
    - If the model has inputs, ``f!`` is ``f_<slug>!(du, u, p, t, inp)`` where
      ``inp[j]`` follows ``ir.inputs`` declaration order.

    Locals from ``ir.locals`` are emitted as sequential scalar assignments in IR
    order before differential (and output) right-hand sides, matching the MTK
    lowering order.
    """
    slug = julia_model_slug(ir)
    f_name = f"f_{slug}!"
    lines: list[str] = []

    lines.append(f"# Generated by {GENERATOR}. Do not edit by hand.")
    lines.append("# Source of truth: the canonical IR. Regenerate after IR changes.")
    if ir.provenance is not None:
        lines.append(f"# IR tool: {ir.provenance.tool}")
        if ir.provenance.content_hash:
            lines.append(f"# IR content hash: {ir.provenance.content_hash}")
    lines.append(f"# IR version: {ir.ir_version}")
    lines.append("")
    lines.append("# --- Numerical view conventions (1-based) ---")
    if ir.states:
        order = ", ".join(s.name for s in ir.states)
        lines.append(f"# u[1:{len(ir.states)}]  == states ({order})")
    if ir.parameters:
        order = ", ".join(p.name for p in ir.parameters)
        lines.append(f"# p[1:{len(ir.parameters)}] == parameters ({order})")
    if ir.inputs:
        order = ", ".join(v.name for v in ir.inputs)
        lines.append(f"# inp[1:{len(ir.inputs)}] == inputs ({order})")
    if ir.equations.outputs:
        order = ", ".join(o.output for o in ir.equations.outputs)
        lines.append(f"# y[1:{len(ir.equations.outputs)}] == outputs ({order})")
    lines.append("")

    state_index = {s.name: i + 1 for i, s in enumerate(ir.states)}
    for diff in ir.equations.differential:
        if diff.state not in state_index:
            raise JuliaCodegenError(
                f"differential equation state {diff.state!r} is not in ir.states"
            )

    if ir.inputs:
        sig = f"function {f_name}(du, u, p, t, inp)"
        extra_doc = (
            "`inp` is a vector with one component per declared input, in IR declaration order."
        )
    else:
        sig = f"function {f_name}(du, u, p, t)"
        extra_doc = "No external inputs; signature is `f!(du, u, p, t)`."

    lines.append(f'"""In-place ODE RHS for `{ir.model.name}` ({extra_doc})"""')
    lines.append(sig)
    for i, s in enumerate(ir.states):
        lines.append(f"    {s.name} = u[{i + 1}]")
    if ir.parameters:
        if len(ir.parameters) == 1:
            lines.append(f"    {ir.parameters[0].name} = p[1]")
        else:
            names = ", ".join(par.name for par in ir.parameters)
            rhs = ", ".join(f"p[{j + 1}]" for j in range(len(ir.parameters)))
            lines.append(f"    {names} = {rhs}")
    if ir.inputs:
        for j, vin in enumerate(ir.inputs):
            lines.append(f"    {vin.name} = inp[{j + 1}]")
    for local in ir.locals:
        lines.append(f"    {local.name} = {expr_to_julia(local.expr)}")
    for diff in ir.equations.differential:
        idx = state_index[diff.state]
        lines.append(f"    du[{idx}] = {expr_to_julia(diff.rhs)}")
    lines.append("    return nothing")
    lines.append("end")
    lines.append("")

    if ir.equations.outputs:
        out_name = f"outputs_{slug}!"
        if ir.inputs:
            sig_o = f"function {out_name}(y, u, p, t, inp)"
        else:
            sig_o = f"function {out_name}(y, u, p, t)"
        lines.append(
            f'"""Fill output vector `y` for `{ir.model.name}` '
            f'(same `u`/`p`/`inp` packing as `{f_name}`)."""'
        )
        lines.append(sig_o)
        for i, s in enumerate(ir.states):
            lines.append(f"    {s.name} = u[{i + 1}]")
        if ir.parameters:
            if len(ir.parameters) == 1:
                lines.append(f"    {ir.parameters[0].name} = p[1]")
            else:
                names = ", ".join(par.name for par in ir.parameters)
                rhs = ", ".join(f"p[{j + 1}]" for j in range(len(ir.parameters)))
                lines.append(f"    {names} = {rhs}")
        if ir.inputs:
            for j, vin in enumerate(ir.inputs):
                lines.append(f"    {vin.name} = inp[{j + 1}]")
        for local in ir.locals:
            lines.append(f"    {local.name} = {expr_to_julia(local.expr)}")
        for k, out in enumerate(ir.equations.outputs, start=1):
            lines.append(f"    y[{k}] = {expr_to_julia(out.rhs)}")
        lines.append("    return nothing")
        lines.append("end")
        lines.append("")

    return "\n".join(lines)
