"""Python numerical backend: IR -> RHS and output functions."""

from __future__ import annotations

import keyword

from model_parser.ir import Call, Expr, IRModel, Num, Sym

GENERATOR = "model-parser python backend"

_INFIX: dict[str, str] = {
    "+": "+",
    "-": "-",
    "*": "*",
    "/": "/",
    "^": "**",
    "==": "==",
    "!=": "!=",
    "<": "<",
    ">": ">",
    "<=": "<=",
    ">=": ">=",
}

_FUNCS: dict[str, str] = {
    "max": "max",
    "min": "min",
    "sqrt": "sqrt",
    "exp": "exp",
    "log": "log",
    "abs": "abs",
    "ifelse": "_ifelse",
}

_RESERVED_NAMES = frozenset(
    {"t", "state", "parameters", "inputs", "_ifelse", "max", "min", "sqrt", "exp", "log", "abs"}
)


class PythonCodegenError(ValueError):
    """Raised when an IR construct cannot be lowered to Python."""


def expr_to_python(expr: Expr) -> str:
    """Render an IR expression as a parenthesized Python expression string."""
    if isinstance(expr, Num):
        return repr(expr.value)
    if isinstance(expr, Sym):
        _require_identifier(expr.name)
        return expr.name
    if isinstance(expr, Call):
        return _render_call(expr)
    raise PythonCodegenError(f"unknown expression node: {expr!r}")


def emit_python(ir: IRModel) -> str:
    """Generate Python functions for the numerical RHS and optional outputs.

    The generated ``f_<slug>(t, state, parameters[, inputs])`` follows the
    argument order used by SciPy ODE solvers. It returns derivatives in state
    declaration order. ``outputs_<slug>`` uses the same arguments and returns
    output equations in declaration order.
    """
    slug = _model_slug(ir)
    function_name = f"f_{slug}"
    state_index = {state.name: index for index, state in enumerate(ir.states)}
    _validate_bound_names(ir)

    for equation in ir.equations.differential:
        if equation.state not in state_index:
            raise PythonCodegenError(
                f"differential equation state {equation.state!r} is not in ir.states"
            )

    lines = [
        f"# Generated by {GENERATOR}. Do not edit by hand.",
        "# Source of truth: the canonical IR. Regenerate after IR changes.",
    ]
    if ir.provenance is not None:
        lines.append(f"# IR tool: {ir.provenance.tool}")
        if ir.provenance.content_hash:
            lines.append(f"# IR content hash: {ir.provenance.content_hash}")
    lines.extend(
        [
            f"# IR version: {ir.ir_version}",
            "",
            "from math import exp, log, sqrt",
            "",
            "",
            "def _ifelse(condition, if_true, if_false):",
            "    return if_true if condition else if_false",
            "",
            "",
            "# --- Numerical view conventions (0-based) ---",
        ]
    )
    if ir.states:
        order = ", ".join(state.name for state in ir.states)
        lines.append(f"# state[0:{len(ir.states)}] == states ({order})")
    if ir.parameters:
        order = ", ".join(parameter.name for parameter in ir.parameters)
        lines.append(f"# parameters[0:{len(ir.parameters)}] == parameters ({order})")
    if ir.inputs:
        order = ", ".join(model_input.name for model_input in ir.inputs)
        lines.append(f"# inputs[0:{len(ir.inputs)}] == inputs ({order})")
    if ir.equations.outputs:
        order = ", ".join(output.output for output in ir.equations.outputs)
        lines.append(f"# return[0:{len(ir.equations.outputs)}] == outputs ({order})")
    lines.append("")

    signature = _signature(function_name, has_inputs=bool(ir.inputs))
    lines.append(f"def {signature}:")
    lines.append('    """Return derivatives in IR state declaration order."""')
    _append_bindings(lines, ir)
    derivatives = [""] * len(ir.states)
    for equation in ir.equations.differential:
        derivatives[state_index[equation.state]] = expr_to_python(equation.rhs)
    lines.append(f"    return [{', '.join(derivatives)}]")
    lines.append("")

    if ir.equations.outputs:
        output_name = f"outputs_{slug}"
        lines.append("")
        lines.append(f"def {_signature(output_name, has_inputs=bool(ir.inputs))}:")
        lines.append('    """Return values in IR output declaration order."""')
        _append_bindings(lines, ir)
        outputs = ", ".join(expr_to_python(output.rhs) for output in ir.equations.outputs)
        lines.append(f"    return [{outputs}]")
        lines.append("")

    return "\n".join(lines)


def _render_call(call: Call) -> str:
    if call.op == "neg":
        if len(call.args) != 1:
            raise PythonCodegenError("'neg' expects exactly one argument")
        return f"(-{expr_to_python(call.args[0])})"
    if call.op in _INFIX:
        if len(call.args) != 2:
            raise PythonCodegenError(f"operator {call.op!r} expects two arguments")
        left, right = (expr_to_python(arg) for arg in call.args)
        return f"({left} {_INFIX[call.op]} {right})"
    if call.op in _FUNCS:
        rendered = ", ".join(expr_to_python(arg) for arg in call.args)
        return f"{_FUNCS[call.op]}({rendered})"
    raise PythonCodegenError(f"unsupported operator/function {call.op!r}")


def _model_slug(ir: IRModel) -> str:
    name = ir.model.name or "model"
    cleaned = "".join(
        character if character.isalnum() or character == "_" else "_" for character in name
    )
    if not cleaned or not cleaned.isidentifier() or keyword.iskeyword(cleaned):
        cleaned = f"m_{cleaned}"
    return cleaned


def _require_identifier(name: str) -> None:
    if not name.isidentifier() or keyword.iskeyword(name):
        raise PythonCodegenError(f"symbol {name!r} is not a valid Python identifier")


def _validate_bound_names(ir: IRModel) -> None:
    for variable in [*ir.states, *ir.parameters, *ir.inputs, *ir.locals]:
        _require_identifier(variable.name)
        if variable.name in _RESERVED_NAMES:
            raise PythonCodegenError(
                f"symbol {variable.name!r} conflicts with the generated Python runtime"
            )


def _signature(name: str, *, has_inputs: bool) -> str:
    arguments = "t, state, parameters, inputs" if has_inputs else "t, state, parameters"
    return f"{name}({arguments})"


def _append_bindings(lines: list[str], ir: IRModel) -> None:
    for index, state in enumerate(ir.states):
        lines.append(f"    {state.name} = state[{index}]")
    for index, parameter in enumerate(ir.parameters):
        lines.append(f"    {parameter.name} = parameters[{index}]")
    for index, model_input in enumerate(ir.inputs):
        lines.append(f"    {model_input.name} = inputs[{index}]")
    for local in ir.locals:
        lines.append(f"    {local.name} = {expr_to_python(local.expr)}")
